server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_classroom?serverTimezone=GMT
    username: root
    password:


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.etjava.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



